### ISSUE TITLE
Warning: Control is changing an uncontrolled input of type text to be controlled

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#714] opened 2017-03-21 09:16 UTC
With this very simple form (almost copied pasted from the doc), I get the below warning when typing a value in the first text input:
```
			<LocalForm
				onSubmit={(values) => handleSubmit(values)}
			>
				<FormattedMessage id="login-lbl-01" />
				<Control.text model=".username" />
				<FormattedMessage id="login-lbl-02" />
				<Control.text model=".password" />
				<Control.checkbox model=".remember" />
				<FormattedMessage id="login-lbl-03" />
				<button type="submit"><FormattedMessage id="login-lbl-04" /></button>
			</LocalForm>
```

```
Warning: Control is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```

Any idea why ?

I'm using:
```
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-intl": "^2.2.3",
    "react-redux": "^5.0.3",
    "react-redux-form": "^1.8.1",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.2",
    "redux-thunk": "^2.2.0"
```

**Comment by chanakasan** [comment] 2017-03-21 10:17
@zabojad I see the same thing and I'm using `v1.8.1` as well.
I'll try to reproduce this in a codepen.

**Comment by davidkpiano** [comment] 2017-03-21 12:27
Most likely a duplicate of #630 - I will publish a patch soon!

**Closed by davidkpiano** 2017-03-21 12:27 UTC

**Comment by dragGH102** [comment] 2017-03-29 11:07
same issue here

**Comment by davidkpiano** [comment] 2017-03-29 14:07
@dragGH102 Publishing a patch soon!
