### ISSUE TITLE
React Calling <Control uncontrolled

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#733] opened 2017-04-05 11:57 UTC
### The Problem
For whatever reason I am getting an errors that my react-redux-form controls are uncontrolled.

### Steps to Reproduce
Seems to have started when I started to try to dynamically pick controls.
```
Steps.getControlByType = (step) => {
  switch (step.typeselect) {
    case types.FORM_TEXT:
      return (<Control.text className="form-control"
                            updateOn={UPDATE_ON}
                            model={step.name}
                            placeholder={step.placeholder}
      />);
    case types.FORM_SELECT:
      return (<Control.select className="form-control"
                              updateOn={UPDATE_ON}
                              model={step.name}
      >
        <option value="">{step.placeholder}</option>
        {step.enumeration.sort((a, b) => {
          return a.displayOrder - b.displayOrder;
        }).map((choice) =>
          <option key={choice.value} value={choice.value}>{choice.label}</option>
        )}
      </Control.select>);
    default:
      break;
  }
};
```

### Expected Behavior
Not to have react tell me its uncontrolled

### Actual Behavior
It is listed as uncontrolled

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa))

**Comment by davidkpiano** [comment] 2017-04-05 13:55
Can you make a minimally reproducible test for this (using the codepen template)?

**Comment by greghawk** [comment] 2017-04-05 13:57
I will try. It's a little tricky with the custom reducer that is modeled() and all.

On Apr 5, 2017, at 9:55 AM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you make a minimally reproducible test for this (using the codepen template)?

**Comment by greghawk** [comment] 2017-04-05 15:07
@davidkpiano One thing that may be related and i am getting a state mutate on dispath for $forms issue as well is that I am using the reduxImmutableStateInvariant middleware. Is that a problem with using this library?

**Comment by davidkpiano** [comment] 2017-04-05 15:20
> I am using the reduxImmutableStateInvariant middleware. Is that a problem with using this library?

Not too sure about that, can you copy/paste the error?

**Comment by greghawk** [comment] 2017-04-05 15:26
@davidkpiano Uncaught Error: A state mutation was detected inside a dispatch, in the path: `forms.$form.value.formModel`. Take a look at the reducer(s) handling the action {"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/personal/FirstName","search":"","hash":"","state":null,"action":"PUSH","key":"rnpclt","query":{},"$searchBase":{"search":"","searchBase":""}}}.

**Comment by greghawk** [comment] 2017-04-05 15:27
I am listening to react-router-redux for path changes and picking currently displayed steps (wizard style)

**Comment by greghawk** [comment] 2017-04-05 15:30
This is the model i am using.  It basically is a dynamically loaded json model.
![image](https://cloud.githubusercontent.com/assets/5090707/24713282/324abfbe-19f3-11e7-89b9-ad4ca3eac01d.png)

**Comment by greghawk** [comment] 2017-04-05 15:32
import {combineReducers} from 'redux';
import { routerReducer} from 'react-router-redux';
import initialStateReducer  from './initialStateReducer';
import offersReducer from './offerPageReducer';
```
import formReducer from './formReducer';
import {createForms} from 'react-redux-form';

const rootReducer = combineReducers({
  initialState: initialStateReducer,
  offerData: offersReducer,
    ...createForms({formModel: formReducer}),
  routing: routerReducer
});
export default rootReducer;
```

formReducer from above
```
import * as types from '../actions/formActionTypes';
import objectAssign from 'object-assign';

export default function formReducer(state = {formId: "", currentSteps: [], steps: [], buttonText: 'Continue'}, action) {

  switch (action.type) {
    case '@@router/LOCATION_CHANGE':
      let segments = action.payload.pathname.split('/');
      let currentSteps = [];
      if (state.steps.length > 0)
        currentSteps = getCombinedSteps(state.steps, segments[2]);
      return objectAssign({}, state, {currentSteps: currentSteps, stepId: segments[2]});
    case types.SET_FORM_STEP:
      return objectAssign({}, state, {stepId: action.stepId});
    case types.FORM_LOADING:
      return objectAssign({}, state, {formId: action.formId});
    case types.FORM_LOADED:
      return objectAssign({}, state, {currentSteps: getCombinedSteps(action.steps, state.stepId), steps: action.steps});
    case types.OUT_OF_WALLET: {
      let mystate = Object.assign({}, state.steps);
      mystate.steps.push(...action.formModel.steps);
      return objectAssign({}, state, mystate);
    }
    case types.INTEL_DATA_COMPLETE:
      return objectAssign({}, state,  action.filterCount);
    default:
      return state;
  }
}

function getCombinedSteps(stepArray, startStepName) {
  let currentSteps = [];
  let startIndex = stepArray.findIndex((item) => item.name === startStepName);

  for (const [index, step] of stepArray.entries()) {
    if (index < startIndex)
      continue;
    currentSteps.push(step.name);
    if (step.addnext === false) {
      break;
    }
  }
  return currentSteps;
}
```

**Comment by davidkpiano** [comment] 2017-04-05 15:47
> @davidkpiano Uncaught Error: A state mutation was detected inside a dispatch, in the path: forms.$form.value.formModel. Take a look at the reducer(s) handling the action {"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/personal/FirstName","search":"","hash":"","state":null,"action":"PUSH","key":"rnpclt","query":{},"$searchBase":{"search":"","searchBase":""}}}.

From what you showed me here, looks like the error might be related to `react-router-redux`.

**Comment by greghawk** [comment] 2017-04-05 15:52
I still get the uncontrolled component switching to controlled regardless of removing that middleware. As far as changing the model on url (history change) do you suggest a different method? I am having difficulty getting react-router to play nice with form models in a wizard concept

**Comment by greghawk** [comment] 2017-04-05 15:54
This is the action on my formReducer that is causing the issue.

```
export function handleNextSteps(formModel) {
  return function (dispatch) {
    dispatch(push('/' + formModel.formId + '/FirstName'));
  };
}
```

**Comment by davidkpiano** [comment] 2017-04-05 15:54
Personally, I just call `history.push` (or from the `router` from context) and bypass Redux completely - I find it unnecessary to keep route state in two separate locations. Try doing that and see if it fixes your problems.

**Comment by greghawk** [comment] 2017-04-05 15:58
So I need to read the Url for the stepId and then set that stepId in the model that the form uses in order to update what step is displayed.  Either way I am updating redux state as that is the state of the app at that url. What is your reducer doing that could be mutating state at the internal modeled copy?

**Comment by greghawk** [comment] 2017-04-05 15:59
I'll try history push but I need to react to it changing

**Comment by greghawk** [comment] 2017-04-05 16:02
Let's ignore that for now. I'll find another way.  What about the uncontrolled issue?

**Comment by davidkpiano** [comment] 2017-04-05 16:28
What version do you have? The uncontrolled warning was recently fixed.

**Comment by greghawk** [comment] 2017-04-05 16:29
4.5.0

**Comment by davidkpiano** [comment] 2017-04-05 16:39
Try 1.8.3 (latest) - if I recall, this particular issue was fixed in 1.8.2.

**Comment by greghawk** [comment] 2017-04-05 16:40
Just tried. No dice

**Comment by greghawk** [comment] 2017-04-05 16:46
I am going to simplify my custom reducer.  I have other pieces in there that are not form elements and maybe that is confusing it.  Not sure what else to do

**Closed** 2017-04-09 02:49 UTC
