### ISSUE TITLE
validateOn="change" doesn't work with checkbox 

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#454] opened 2016-10-07 09:43 UTC
Hi,
simple issue: I have a `Control.checkbox` and want it to be validated on `change`. It seems it is broken on `v1.0.8`:
```jsx
// validator
function hasToBeTrue(value) {
    if (value === false || typeof value !== 'boolean') {
        return false;
    }
    return true;
}

// control
<Control.checkbox
    model={'myForm.checkMe'}
    validators={{ hasToBeTrue }}
    validateOn={['change', 'blur']}
/>
```
It works with on `blur` but it do not work with on `change`.

**Comment by davidkpiano** [comment] 2016-10-12 04:30
@MiMaMuh I cannot reproduce this in the latest RRF version, thankfully. My guess is that it was fixed as a side effect of #440.

**Comment by MiMaMuh** [comment] 2016-10-12 08:06
@davidkpiano Thx, yes, it works with `v1.0.10` as long as I do not pass a custom `validateOn` prop. When I pass a custom validate prop like `validateOn={['change']}` it starts to validate only on blur and it doesn't matter if I pass `validateOn={['focus', 'change', 'blur']}` or `validateOn={['focus', 'change']}` ...

It seems, it gets buggy when I start to pass the `validateOn` prop.

**Comment by davidkpiano** [comment] 2016-10-12 12:26
@MiMaMuh Can you please make a reproducible example? I've done that and still can't reproduce it. Here's a boilerplate: https://esnextb.in/?gist=b31277251f5c24df9b13b2cc95abc00c

**Comment by MiMaMuh** [comment] 2016-10-12 12:59
@davidkpiano yes, of course:
https://esnextb.in/?gist=e516266426da03e90e42e218e070c848

I added both examples, the working checkbox and the buggy checkbox. It seems, the working checkbox without the `validateOn` prop fires the action `rrf/setErrors` directly after `rrf/change` which the buggy checkbox doesn't do.

**Comment by davidkpiano** [comment] 2016-10-12 13:15
@MiMaMuh Fixed now! Sorry, here was the issue:

```diff
      if ((validators || errors)
        && fieldValue
        && !fieldValue.validated
-       && validateOn === 'change'
+       && containsEvent(validateOn, 'change')
      ) {
        this.validate();
      }
```

**Closed** 2016-10-12 13:14 UTC
Labels: can't reproduce

**Comment by MiMaMuh** [comment] 2016-10-12 13:48
@davidkpiano Thank you for your help, work and this great lib! 👍
