### ISSUE TITLE
Trigger submit() on Form RRF component

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#285] opened 2016-06-17 10:13 UTC
How can I trigger a submit() (like the [HTML Form Element `submit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit)) from js on a RRF `Form` component ?

It seems that setting a ref on the `Form` instance won't help as it does not have any `submit` method...

Also, submitting the generated form element (with a `querySelector("form").submit()`) oddly reloads the page and concats `?<fieldname>=<fieldvalue>` to the url...

I have to do that because my submit button is outside of the Form...

**Comment by zabojad** [comment] 2016-06-17 15:39
@davidkpiano what about adding a `submit()` method to RRF `Form`? that we would call via

**Comment by zabojad** [comment] 2016-06-17 23:05
I'm having another case where I would need this: on some form, I need the checkboxes to trigger their form to be submit when they get checked... How could I achieve that?

**Comment by davidkpiano** [comment] 2016-06-17 23:36
I'll have a fix for this soon - the issue is that directly calling `submit()` on the form node will do the default action of submitting the form the HTML5 way.

**Comment by zabojad** [comment] 2016-06-18 07:30
@davidkpiano is there any temporary workaround I could use (for example some hidden method on the RRF `Form` component for example) until you come back with some API to submit a `Form`?

**Closed** 2016-07-02 17:40 UTC
Labels: question

**Comment by davidkpiano** [comment] 2016-07-02 17:42
This is now fixed! See here: https://github.com/davidkpiano/react-redux-form/issues/296#issuecomment-230113569
