### ISSUE TITLE
Add an auto-complete example?

### ISSUE THREAD

**Issue by Ahmtdnz** [davidkpiano/react-redux-form#274] opened 2016-06-11 17:09 UTC
İ have [react-select](http://jedwatson.github.io/react-select/) but react-select(event.target.value) == null

Thanks for help. Have a nice day.

**Comment by davidkpiano** [comment] 2016-06-11 18:43
If possible, can you reproduce the issue inside of www.esnextb.in ?

**Comment by Ahmtdnz** [comment] 2016-06-11 21:43
it is [here.](http://esnextb.in/?gist=910c97a242a1c47b967c5b4a09d0c5c3)
but [react-select ](http://jedwatson.github.io/react-select/) doesn't work with [](http://esnextb.in/).
i have "react-select": "^1.0.0-beta13" .

**Comment by davidkpiano** [comment] 2016-06-11 21:50
The first thing I noticed was that your `<Select>` component is inside a `<Field>` that doesn't know what kind of component that is. Have you read the [documentation on custom components](https://davidkpiano.gitbooks.io/react-redux-form/content/custom_components.html)?

**Comment by davidkpiano** [comment] 2016-06-13 15:22
I'll close this for now, since it's a usage question and not an issue. If you encounter any bugs while trying to implement RRF into React-Select, feel free to open another issue.

**Closed by davidkpiano** 2016-06-13 15:22 UTC
Labels: question
