### ISSUE TITLE
actions.setErrors(), actions.setValidity() brakes form.onSubmit()

### ISSUE THREAD

**Issue by venelin-mihaylov** [davidkpiano/react-redux-form#291] opened 2016-06-19 08:32 UTC
I want to manually set field's errors - `actions.setErrors(fieldName, 'too many errors')`. It's ok. Then I clear the errors manually, with `actions.setValidity(fieldName, true);`
Then I call `form.onSubmit()`, which instead of calling it's `onSubmit` prop, marks the forms as invalid ...
The form triggers actions

``` js
rrf/setSubmitFailed = {
fieldsValidity: null,
options: {
errors: true
}
};
rrf/setFieldsValidity = {
fieldsValidity: null,
options: {
errors: true
}
};
```

Am I doing something wrong, or this is a bug?
Is it possible `onSubmit()` the form to validate it's fields only with client side validation rules and override any manually set errors?

example:

``` js
//entity = 'tournament'
//formModel('tournament') === 'tournamentModel',
//formModelField('tournament','name') === 'tournamentModel.name'

export default class TournamentForm extends React.Component {

  render() {
    const {
      dispatch,
      onSubmit,
      onReset,
      entity,
      redux: {
        globalError,
        saving,
        loading
      },
      form
    } = this.props;

    return (
      <div>
        {loading && <p>Loading...</p>}
        {saving && <p>Saving ...</p>}
        {globalError && <p>global error:{globalError}</p>}
        <Form onSubmit={onSubmit} model={formModel(entity)}>
          <MaterialField model={formModelField(entity, 'name')}>
            <TextField
              required
              hintText="name"
              floatingLabelText="name"
              errorText={MUIErrorText(form, entity, 'name')}
            />
          </MaterialField>

          <br/>
          <RaisedButton label="Submit"
                        primary={true}
                        type="submit"
                        style={{margin: 5}}
          />
          <RaisedButton label="Reset"
                        secondary={true}
                        onClick={onReset}
                        style={{margin: 5}}

          />


          <RaisedButton label="errors"
                        secondary={true}
                        onClick={() => {
                          dispatch(actions.setErrors(formModelField('tournament', 'name'), 'too many errors'));
                        }}
                        style={{margin: 5}}
          />

          <RaisedButton label="clear errors"
                        secondary={true}
                        onClick={() => {
                          dispatch(actions.setErrors(formModelField('tournament', 'name'), false));
                          dispatch(actions.setValidity(formModelField('tournament', 'name'), true));
                        }}
                        style={{margin: 5}}
          />
        </Form>
      </div>
    )
  }
}
```

reducers:

``` js
const rootReducer = combineReducers({
 // ...
 tournamentModel: modelReducer('tournamentModel', {}),
 tournamentForm: formReducer('tournamentModel', {}),
// ...
})
```

**Comment by davidkpiano** [comment] 2016-06-21 16:12
Can you put this in an www.esnextb.in so I can better diagnose the issue?

**Comment by davidkpiano** [comment] 2016-07-02 18:57
@venelin-mihaylov Any updates on this?

**Comment by davidkpiano** [comment] 2016-07-06 13:58
Closing due to inactivity. If you could, please make an www.esnextb.in with the minimal code necessary to reproduce the issue so I could better diagnose.

**Comment by cipater** [comment] 2016-10-16 00:17
I'm running into the same issue... I'm using `setFieldsErrors` to set errors sent back from server-side validation. And subsequent submits fail, emitting a setSubmitFailed action followed by setFieldsValidity. Repeated submits continue to fail. 

Inspecting the form field in question, I see that `valid`, `validated`, `validating`, and `validity` are all `false`.

The documentation notes that `It simultaneously sets the .validity on each sub-model to the inverse of its errors.` Am I supposed to be cleaning up the `valid` and/or `validity` keys manually?

**Comment by davidkpiano** [comment] 2016-10-16 01:08
> Am I supposed to be cleaning up the valid and/or validity keys manually?

Ideally no, but that's a good workaround currently. I'll investigate this.

**Comment by cipater** [comment] 2016-10-16 01:20
I added `dispatch(actions.resetValidity(modelName))` to the beginning of my `handleSubmit` function, but that doesn't appear to be working. Perhaps it's the same issue as #463? 

Although, I see that issue was fixed in 1.0.10... and while the `package.json` in my `node_modules/react-redux-form` claims to be 1.0.10, `node_modules/react-redux-form/src/reducers/form/reset-validity-action-reducer.js` does not contain the changes from 3acba22.

**Comment by cipater** [comment] 2016-10-16 01:31
In fact, I'm still experiencing #465 and #466 despite my local copy claiming to be 1.0.10. And that's the case even after deleting and reinstalling the package.

**Comment by cipater** [comment] 2016-10-25 20:32
I'm still experiencing the issue as of `1.0.14`.

Currently the only workaround I've found is to run `actions.resetValidity()` inside an `onClick` handler on the submit button. Otherwise the `handleSubmit` function on the form is never reached on subsequent attempts to submit.

**Comment by cipater** [comment] 2016-10-25 20:48
If it helps, here's a simplified example of what I'm doing:

```javascript
class OrderForm extends React.Component {
  resetForm() {
    dispatch(actions.resetValidity('forms.order.address'))
  }

  handleSubmit(order) {
    dispatch(updateOrder(order))
    .catch(err => dispatch(actions.setFieldsErrors('forms.order.address', err.address)))
  }

  render() {
    return (
      <Form model='forms.order' onSubmit={ this.handleSubmit.bind(this) }>
        { this.props.children }
        <button onClick={ this.resetForm.bind(this) }>Submit</button>
      </Form>
    )
  }
}
```

Perhaps it's because I'm calling `actions.setFieldsErrors()` on a subform that's the issue? I tried `actions.setFieldsErrors('forms.order', { address: err.address })` and wasn't getting the results I was expecting.

**Comment by davidkpiano** [comment] 2016-10-25 23:32
@cipater Is `forms.order.address` an object or a string?

**Comment by cipater** [comment] 2016-10-26 00:30
Yeah that's not clear from the example, sorry. `forms.order.address` is an object. `props.children` contains various `Fieldset`s for the main `order` form. So `err` is an object of the same shape as the root `order` form.

```javascript
{
  address: {
    first_name: "can't be empty",
    ...
  },
  ...
}
```

And since `actions.setFieldsErrors('forms.order', err)`  wasn't working, I'm calling `setFieldsErrors` for each object within `err`. But it would be nice if `setFieldsErrors` (or some other method) could handle nested objects.

**Comment by davidkpiano** [comment] 2016-11-04 15:09
Is this still an issue with the latest version? @cipater

**Comment by cipater** [comment] 2016-11-11 20:11
Sorry for the delayed response... Yes, this is still an issue as of `1.0.14`, which I believe was current at the time of you asking.

**Comment by cipater** [comment] 2016-11-11 20:20
Hmm. Looking at the commit logs, that doesn't appear to be true... But I've just tried it on `1.2.2`, and it's still an issue.

**Comment by davidkpiano** [comment] 2016-11-16 14:53
@cipater: The problem with using `setFieldsErrors()` with this error structure:

```
{
  address: {
    first_name: "can't be empty",
    ...
  },
  ...
}
```

is that RRF has no way of knowing if `'first_name'` is an error key or a model key. As a counterexample, I'm working with an API which returns errors as arrays; e.g.;

```
{ credit_card: ['Number is invalid', 'Card is expired'] }
```

And it would be erroneous for RRF to assume that we were talking about `credit_card[0]` and `credit_card[1]`.

Your approach of manually validating is the correct approach; RRF would become severely bloated if it tried to handle every possible API approach to sending back async errors.

To make your life easier, I recommend a package such as [`flat`](https://www.npmjs.com/package/flat) to flatten nested structures. Then, you can pass this directly into `setFieldsErrors(model, flattenedErrors)`.

**Closed by davidkpiano** 2016-11-16 14:53 UTC
