### ISSUE TITLE
Splits errors on every word

### ISSUE THREAD

**Issue by Venumteam** [davidkpiano/react-redux-form#824] opened 2017-06-04 16:44 UTC
Hey, I have a drawer with tabs, in one tab I have input - when I entered not valid data, it shows me error as I expected, but when I change the tab and then switch back,  an error message is divided into each letter. What could be the problem?
p.s. sorry for my English
<img width="398" alt="2017-06-04 19 42 32" src="https://cloud.githubusercontent.com/assets/13667226/26763598/0329c8e8-495e-11e7-8596-96c22e942ab4.png">
<img width="1075" alt="2017-06-04 19 20 58" src="https://cloud.githubusercontent.com/assets/13667226/26763599/068bd224-495e-11e7-80d8-ac1ed9d994fe.png">

**Comment by davidkpiano** [comment] 2017-06-04 17:36
Can you make a quick reproducible example? Use this as a starting point: http://codepen.io/davidkpiano/pen/yJwmEa

**Comment by Venumteam** [comment] 2017-06-04 20:03
hm, for some reason I can't reproduce this bug in codepen, errors works fine there

**Comment by davidkpiano** [comment] 2017-06-04 20:54
Do you have the latest version of RRF? I recall a similar issue a while back (can't find it now) that has been addressed.

**Comment by Venumteam** [comment] 2017-06-04 23:13
I have '1.11.1'v. of RRF I'll try to update to the latest release. Thanks for the advice

**Comment by Venumteam** [comment] 2017-06-05 08:54
Update to the latest version doesn't help me, but I found that this bug Is manifested - only if errors was set by dispatching them manually like this `dispatch(actions.setErrors('forms.register.email', registerMessages.email.used));`

**Comment by leoalves** [comment] 2017-06-16 03:48
The validator has to be a function or object. 
That's why the second option gives the error it cannot be a string.
With actions.resetValidity(model, [omitKeys]) you can reset the error.

**Comment by davidkpiano** [comment] 2017-07-19 14:45
> hm, for some reason I can't reproduce this bug in codepen, errors works fine there

Marking this as "can't reproduce", please submit a CodePen example (with the latest version) if you are still able to reproduce it.

**Closed by davidkpiano** 2017-07-19 14:45 UTC
Labels: can't reproduce
