### ISSUE TITLE
Errors component outputs error when using nested reducers

### ISSUE THREAD

**Issue by morsdyce** [davidkpiano/react-redux-form#162] opened 2016-04-26 15:51 UTC
When using the Errors component with a nested reducer I get the following error:
`Cannot read property 'valid' of null`

I made a codepen with the use case I'm trying to achieve based on the sync validation recipe.
http://codepen.io/morsdyce/pen/QNVrzg

Is there something I'm missing?

**Comment by davidkpiano** [comment] 2016-04-26 16:41
No, this is a bug that you've found. Sorry about that!

The issue is in these two functions: https://github.com/davidkpiano/react-redux-form/blob/master/src/utils/index.js#L52-L65 it can find shallow-nested forms just fine, but chokes when it comes to deeper forms. I'll have a fix for this later today, unless you feel like tackling it :)

**Comment by morsdyce** [comment] 2016-04-26 16:53
No need to be sorry, you've built the only redux forms library that actually makes sense!

I tried debugging it and found it being caused in the following line:
https://github.com/davidkpiano/react-redux-form/blob/5367a7a2c91689811cdff8db4e1ccfd062049547/src/utils/index.js#L60

But I'm not sure which parts of the model string I'm supposed to take.
In my example its forms.register.username, my guess is taking everything until the last dot. but I'm not sure.

**Comment by davidkpiano** [comment] 2016-04-26 17:13
I need to refactor this. Should be a really simple refactor, though.

Here's the rough draft of the algorithm I want to use:
- Split the `model` path (using `toPath(model)`), take the first segment, `get()` the state slice from it.
- Check: is that state slice a form and `startsWith(model, form.model)` true?
  - If true, return that state slice, because it's the form we're looking for.
  - Otherwise, repeat recursively.
- Memoize finding the key, because the store shape is never going to change.

**Comment by morsdyce** [comment] 2016-04-27 07:10
I tried working on it and had allot of issues with the dev environment (running only 1 test) and in general working on it.

I would appreciate if you could take a look at it

**Comment by davidkpiano** [comment] 2016-04-27 15:04
This will be released in the next patch @morsdyce !

**Closed** 2016-04-27 15:03 UTC
Labels: bug
