### ISSUE TITLE
defaultProps on custom components override react-redux-form onChange prop

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#77] opened 2016-03-19 00:10 UTC
Was trying to get this library working with [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize).

Was following along with your examples of using [Custom Components](https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html) but could not get it to work with the change handler.

I replicated the problem with an example based on your create-field-component.spec.js.
Not sure if its a bug but it was confusing.

```
const emptyFunction = function() {};

class FamiliarText extends React.Component {

	render() {
		const { onChange } = this.props;

		return (
			<div>
				<input onChange={e => onChange(e)} />
			</div>
		);
	}
}

FamiliarText.defaultProps = {
	onChange: emptyFunction
};

const CustomField = createFieldClass({
	FamiliarText: controls.text
});

<CustomField model={model}>
    <FamiliarText />
</CustomField>
```

I think the issue is [line 18](https://github.com/davidkpiano/react-redux-form/blob/e0e67137d00887bd240f6157d91e81ff62704d08/src/components/control-component.js#L18) in Control's render method where it includes the spread from the controls props.  At this point the defaultProp which is an empty function seems to overwrite the onChange handler installed by react-redux-form.

**Comment by davidkpiano** [comment] 2016-03-19 16:04
Duplicate of #74, but I've recently pushed a commit that changes the priority of the control's own props in the prop mapping, as suggested in #74: https://github.com/davidkpiano/react-redux-form/commit/a78d19b39f0e6341506115f5b5e0cfa221639233

Can you do me a favor and try it out with `react-redux-form@0.8.9` to see if that fixes the issue?

**Comment by davidkpiano** [comment] 2016-03-19 16:07
Okay, the change is published under `react-redux-form@0.8.10`. Try it out! :)

**Comment by mdgbayly** [comment] 2016-03-19 16:51
D'oh how did I miss that duplicate...

Tried it out - seems to resolve the issue for me. Thanks!

**Comment by davidkpiano** [comment] 2016-03-19 16:56
Fantastic! Thank you for verifying!

**Closed by davidkpiano** 2016-03-19 16:56 UTC
Labels: duplicate

**Comment by mdgbayly** [comment] 2016-03-20 07:00
ha - this came back and bit me in another area of my app...

I'm in the process of converting an app from redux-form to react-redux-form :+1: 

We have an area of our model that is a sparse array so it is not keyed by the order of the fields in the view.  Instead we only add an entry to the array the first time a value is entered in an input in the view. The input fields have an associated identifier (mapKey) that maps them to a specific array entry. This means the order of the entries in the array can be different to the order of the fields in the view.  An example model looks like this:

```
mapEntry: [
    {
        mapKey: 'answer_3',
        mappedValue: '75'
    },
    {
        mapKey: 'answer_1',
        mappedValue: '50'
    }
]
```

We have code like the following that sets up a dummy model entry with an overridden onChange handler. The onChange handler adds a new array entry the first time the user types in a view field.  Subsequently, we setup the model value in the standard way by finding the associated array index.
```
findMapEntry(mapKey) {
  const { mapEntry, dispatch } = this.props;

  const mapEntryIndex = mapEntry.findIndex((entry) => {
    return entry.mapKey === mapKey;
  }) : -1;

  let mappedValue;
  if (mapEntryIndex === -1) {
    mappedValue = {
      onChange: function(e) {
        dispatch(actions.push('mapEntry', {
          mapKey: identifier,
          mappedValue: e.target.value
        }));
      },
      model: ''
    };
  } else {
    mappedValue = {
        model: `mapEntry[${mapEntryIndex}].mappedValue`
    }
  }

  return mappedValue;
}
```

But this code doesn't work with the switch of the props.  I still think switching the ordering of the props is probably the right solution.  But maybe you have some thoughts on the best way to implement the requirement described above?

For now I've worked around it by changing the onChange function in the code above to onChangeOverride and then overridding the props mapping in our custom field.  (The field that represents mappedValue in the above code is alread a custom field).
e.g.

```
const CustomField = createFieldClass({
	MaskedInput: (props) => ({
		...props,
		defaultValue: props.modelValue,
		name: props.model,
		value: props.modelValue,
		onChange: props.model ? props.onChange : props.onChangeOverride
	})
});
```
Perhaps, this is the best solution, or maybe there is a cleaner solution using some reducer tricks?

**Comment by davidkpiano** [comment] 2016-03-20 13:57
This actually looks like the perfect candidate for [normalizr](https://github.com/gaearon/normalizr), that your data can be normalized per its unique keys into dictionaries:

```js
// from ...
mapEntry: [
    {
        mapKey: 'answer_3',
        mappedValue: '75'
    },
    {
        mapKey: 'answer_1',
        mappedValue: '50'
    }
]

// to...
mapEntry: {
  answer_3: { mappedValue: 75 },
  answer_1: { mappedValue: 50 }
}
```

Normalized data is much easier to use in any Redux application, especially React-Redux-Form. Your model can then just become this: `<Field model="mapEntry.answer_1.mappedValue">` without the complex (and somewhat fragile) `onChange` overrides or custom prop mapping.

Is this a viable solution?

**Comment by mdgbayly** [comment] 2016-03-20 14:14
Thanks, I'll give that option some thought.

My first reaction is that it is probably not possible to switch to a format like that, but maybe I'm being blinkered.  That mapEntry data format is being given to our app by a backend service, so the client doesn't really control it.  We could normalize it in the client I suppose and convert back to the API format before sending back to the service, but we're trying to minimize the amount of knowledge in the client.  Also the range of values of the mapKey are out of the control of the client app, so I worry that trying to use them as a property name might cause other issues. But I'll give it some more thought.

My other thought was to dynamically set the FieldComponent.updateOn property to allow sending the array push action the first time the user types in a field.  Seems like that should work but having issues with it at the moment.  But might not be any less fragile that the solution I posted above.

**Comment by mdgbayly** [comment] 2016-03-20 15:03
The normalizr solution looks interesting.  It is certainly a pain to deal with these nested objects in an array. Would be so much cleaner if they were a dictionary like you suggested. The main thing stopping me from adopting it is that we do most validation server side and error responses use JSON pointer to indicate which part of the response is in error.  We use those pointers to dynamically set the validity of our model.  If we used normalizr to change the model client side we'd also have to normalize the JSON pointers somehow too. I guess that would be doable.

Anyway, I have it working with a dynamically set updateOn function now.  That seems less hacky than the original solution I posted as it seems more what it's intended for: 'dispatch custom actions along with the actions.change(...) action'

**Comment by davidkpiano** [comment] 2016-03-20 15:04
Awesome! What do the JSON pointers look like, out of curiosity?

**Comment by mdgbayly** [comment] 2016-03-20 15:08
pretty basic: in the example above we require the mappedValues to be numeric and in the range 0-100%.  So if a client tries to save data like:
```
mapEntry: [
    {
        mapKey: 'answer_3',
        mappedValue: '75'
    },
    {
        mapKey: 'answer_1',
        mappedValue: '110'
    }
]
```
then the error response from the API would contain something like:
```
{
    code: 'TOO_BIG',
    pointer: '/mapEntry/1/mappedValue'
}
```

**Comment by davidkpiano** [comment] 2016-03-20 15:13
Interesting. Still sounds like normalizr might be good, because that can map directly to:

```js
mapEntry: {
  3: { mappedValue: 75 },
  1: { mappedValue: 110 }
}
```

**Comment by mdgbayly** [comment] 2016-03-20 15:27
Interesting idea, but I think we lost the mapKey in your example and unfortunately that is the key relational identifier.  Maybe I'm confusing it by using identifiers like 'answer_1'
```
mapEntry: [
    {
        mapKey: 'apple',
        mappedValue: '75'
    },
    {
        mapKey: 'orange',
        mappedValue: '110'
    }
]
```
```
{
    code: 'TOO_BIG',
    pointer: '/mapEntry/1/mappedValue'
}
```
Normalized
```
mapEntry: {
  apple: { mappedValue: 75 },
  orange: { mappedValue: 110 }
}
```

Now not so straightforward to translate our JSON pointer but probably not rocket science:

Normalized JSON pointer
```
{
    code: 'TOO_BIG',
    pointer: '/mapEntry/orange/mappedValue'
}
```

**Comment by mdgbayly** [comment] 2016-03-20 15:41
To be honest, I'm kind of tempted to change our API to rework that mapEntry format.  It's a royal pain to have to deal with something that is essentially a map as an array.  We're trying to align our API format to an older legacy XML format which is why it looks like that.  I considered changing it to a plain old object where mapKey is just a property name.

The main reason why I didn't do that is because of the issue where we don't control the range of values that can be used for mapKey and I was concerned that a value might be used that would cause issues as a javascript property name e.g. because it clashes with a Javascript reserved name or can't be used with dot notation.  

Out of interest, how is react-redux-form handling these field names internally?  Does everything get referenced using bracket notation (e.g. via icepick), or could there be areas where property names could cause issues with dot notation?

**Comment by davidkpiano** [comment] 2016-03-20 15:51
Yes, every path is referenced using bracket/dot notation, e.g. via icepick and lodash's `path()` for `get()`. That means you should be fine, even if a property name contains spaces or dots, because you can just do this: `"foo.bar["prop with spaces"]["prop.with.dot"].baz"`
