### ISSUE TITLE
Things in devDependencies that don't belong?

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#147] opened 2016-04-19 01:49 UTC
I was just sitting here cursing to myself as I launched an app into production, and react-redux-form totally failed to work. Typing in fields had no effect at all. Then I realized there's quite a long list of stuff in the `devDependencies` section of `package.json`, things like react, redux, etc. Do those really belong there? It seems to me that the following packages belong in `dependencies` instead: (or perhaps `peerDependencies`? I don't know what the difference is)

```
    "estraverse-fb": "^1.3.1", // not sure about this one..
    "immutable": "^3.7.6",
    "react": "^0.14.7",
    "react-addons-test-utils": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-thunk": "^2.0.1",
```

**Comment by davidkpiano** [comment] 2016-04-19 03:33
Interesting. For sure, I know `react`, `react-redux`, and `redux` do belong in dependencies, and they are already there. I'll have to take a look at `react-dom` now - that could be the failure point - that's required for it to work as well.

What exactly was the failure?

**Comment by ffxsam** [comment] 2016-04-19 03:37
I believe they belong in `peerDependencies` actually. That's how material-ui does it, at least.

The failure was that it simply wasn't working. Focusing in a field, typing in it.. none of those triggers Redux at all.

**Comment by davidkpiano** [comment] 2016-04-19 03:39
Alright, I'll release a patch with `redux-thunk` and `react-dom` as `peerDependencies` right now. Can you let me know if that works in a couple minutes?

**Comment by ffxsam** [comment] 2016-04-19 03:42
Absolutely!

**Comment by davidkpiano** [comment] 2016-04-19 03:51
Okay, published as `react-redux-form@0.10.5`. Try it out!

**Comment by ffxsam** [comment] 2016-04-19 03:53
Trying it out now.. (PS, you'll want to remove the stuff in `devDependencies` that you copied over to `peerDependencies`.

**Comment by davidkpiano** [comment] 2016-04-19 03:56
`devDependencies` won't get installed in production builds, so I think we're safe keeping them in there, especially when others are forking the repo. Otherwise, you'd have to manually install them.

**Comment by ffxsam** [comment] 2016-04-19 03:57
The packages in `devDependencies` are covered by being in `peerDependencies` though. `devDependencies` is typically reserved for things like linting, testing, and dev/performance tools only.

**Comment by ffxsam** [comment] 2016-04-19 03:58
Actually on second thought.. material-ui has react in `devDependencies` as well. I'm not sure why. But I'd just model yours after how they structured theirs :)

https://github.com/callemall/material-ui/blob/master/package.json

**Comment by davidkpiano** [comment] 2016-04-19 03:59
It's because `peerDependencies` don't get installed automatically anymore - instead, NPM will just yell at you that they're missing. 😟

**Comment by ffxsam** [comment] 2016-04-19 04:00
Ahhh ok. I'll admit, I don't totally understand npm's package system.

**Comment by ffxsam** [comment] 2016-04-19 04:09
Man, I don't get it. It's still not working in production. Here are two screencaps.. first one is in production, the second is on my local dev machine.
 
![licecap1](https://cloud.githubusercontent.com/assets/12532733/14627476/aa243af6-05a9-11e6-9f00-64fd06be98cd.gif)

![licecap2](https://cloud.githubusercontent.com/assets/12532733/14627485/c7c8ffe2-05a9-11e6-9e04-8f42d8773c61.gif)

**Comment by ffxsam** [comment] 2016-04-19 04:09
But rrf is partially working in production. It can load data. Calls to it don't generate errors, but obviously fields aren't working.

**Comment by davidkpiano** [comment] 2016-04-19 04:14
I have a feeling this has to do with `material-ui` itself, and not RRF. See this issue: https://github.com/davidkpiano/react-redux-form/issues/144

I'm going to investigate `material-ui` though. It makes things a lot more complicated, to say the least.

**Comment by ffxsam** [comment] 2016-04-19 04:16
Oh shoot! Nice find. I've got my own field wrapper I'm using too, BTW:

```
export const MUITextField = createFieldClass({
  TextField: props => ({
    onChange: props.onChange,
    value: props.modelValue,
  }),
});
```

**Comment by davidkpiano** [comment] 2016-04-19 04:21
Can you humor me and try doing it manually? Just to see if this works:

```js
import { actions } from 'react-redux-form';


// ... in render
<Text Field onChange={(e) => dispatch(actions.onChange(e))} />
```

**Comment by ffxsam** [comment] 2016-04-19 04:22
Sure.. but tomorrow morning :)

**Comment by i4got10** [comment] 2016-04-19 06:51
Possible related to https://github.com/davidkpiano/react-redux-form/issues/65

**Comment by davidkpiano** [comment] 2016-04-19 12:38
Good call, @i4got10! @ffxsam, try adding a `displayName` to the component:

```js
import TextField from 'material-ui/...';

TextField.displayName = 'TextField'

I'll open a PR for this in material-ui if that solves the issue. They should ideally have a `displayName` property set.
```

**Comment by Rhywden** [comment] 2016-04-19 15:06
I can submit success!

This indeed solves my issue with the empty model.

**Comment by davidkpiano** [comment] 2016-04-19 15:41
Seems like that was the culprit, @ffxsam ! This will be addressed in v1.0 with the `<Control>` component (details here: https://github.com/davidkpiano/react-redux-form/issues/144#issuecomment-211973693 ), but for now, this workaround is quick and easy:

```js
TextField.displayName = 'TextField';
```

**Closed by davidkpiano** 2016-04-19 15:41 UTC

**Comment by ffxsam** [comment] 2016-04-19 16:24
Yikes - don't use `displayName`. It's an extra step that devs don't really want to have to add into their code. If `xyz` is a React element, use `xyz.constructor.name`.

**Comment by davidkpiano** [comment] 2016-04-19 16:29
> Yikes - don't use displayName. It's an extra step that devs don't really want to have to add into their code. If xyz is a React element, use xyz.constructor.name.

@ffxsam I know. This will be resolved in the upcoming v1.0. This is simply a workaround.

**Comment by ffxsam** [comment] 2016-04-19 16:31
Oops sorry.. I missed the word "workaround" in your comment above 😏

**Comment by ffxsam** [comment] 2016-04-19 16:32
Though I can't seem to figure out how to get the name of a stateless component.

**Comment by ffxsam** [comment] 2016-04-19 16:39
I still don't understand what's causing this to break in production. `displayName`, which RRF relies on, doesn't even exist for me in dev.

**Comment by davidkpiano** [comment] 2016-04-19 16:52
@ffxsam Without seeing your code it's a bit hard to tell... But can you try this?

```js
<TextField onChange={(e) => dispatch(actions.change('foo.bar', e))} />
```

and see if that works in production?

**Comment by ffxsam** [comment] 2016-04-19 16:55
Testing now..

**Comment by ffxsam** [comment] 2016-04-19 17:03
Yes, I see `foo.bar` being changed in the Redux devtools.

**Comment by ffxsam** [comment] 2016-04-19 17:08
An example of my form code:

```
            <MUITextField model="insightModel.title">
              <TextField
                floatingLabelText="Title"
                errorText={getError(fields, 'title')}
              />
            </MUITextField>
```

```
export const MUITextField = createFieldClass({
  TextField: props => ({
    onChange: props.onChange,
    value: props.modelValue,
  }),
});
```

**Comment by davidkpiano** [comment] 2016-04-19 17:08
Okay, then I'm pretty sure that the issue is with the `.displayName` (or `.constructor.name`) not being visible in material-ui. It's unfortunate, but hey.

Manually adding the actions is a decent workaround, and all this will be solved with `<Control>`. It's good to know though that `<Control>` is basically just mapping the actions the same way that you would do it. It just provides a nicer API for doing so.

**Comment by ffxsam** [comment] 2016-04-19 17:14
I still don't get why it breaks in production. `displayName`. If I inspect TextField in the Chrome console, `$r.displayName` and `$r.constructor.displayName` don't exist. And in your code, you're checking for names via:

```javascript
    let controlDisplayName = control.constructor.displayName
      || control.type.displayName
      || control.type.name
      || control.type;
```

`TextField` has none of these properties, yet in dev it works fine. Am I missing something?

>the issue is with the `.displayName` (or `.constructor.name`) not being visible in material-ui. It's unfortunate, but hey.

No, `.constructor.name` actually does work for MUI components:

```
$r.constructor.name
"TextField"
```

**Comment by davidkpiano** [comment] 2016-04-19 17:27
Okay, I'm going to add the check for `control.constructor.name` and test this out locally to see if that fixes the problem.

**Comment by ffxsam** [comment] 2016-04-20 00:16
@davidkpiano What did you find?

**Comment by davidkpiano** [comment] 2016-04-20 00:53
Hosting a React hack a thon right now, nothing yet :)
